### ISSUE TITLE
Manually invoke webhooks

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/feature-requests#102]
Suppose I add an insert webhook to a 3rd party service, but my model already contains data. 

In this case, it would be nice to have a way to trigger the webhook for the data that's already existing. 

Manually triggering the webhook for a selected node could also be a very powerful testing/debugging tool.

**Comment by marktani** [comment]
That's a great idea! Related to #35

**Comment by marktani** [comment]
This can now be done using the fullscreen mode for Graphcool Functions. Here's more information: https://github.com/graphcool/feature-requests/issues/30#issuecomment-306043378.
