### ISSUE TITLE
Collaborator invite link

### ISSUE THREAD

**Issue by sedubois** [graphcool/feature-requests#105]
I get this error when adding a collaborator: `No Graphcool user exists with the email 'XXX'. Please ask your collaborator to create a Graphcool account.`

It would be great to avoid this extra step: just send an invite link to that email, so that the person can sign up and directly get access to the project.

**Comment by marktani** [comment]
Thanks, that's a great addition to the collaboration feature :+1:

**Comment by sedubois** [comment]
Also to reduce friction even more, it'd be great to copy/paste an invite link (e.g to give to my collaborator directly in our chat program).

**Comment by divyenduz** [comment]
It would also help in a freelancer's use case. For example, some freelancing providers do not allow sharing of the email but a copy/paste invite link will work.

**Comment by marktani** [comment]
This is available for quite some time already. You can now invite any email address and depending on if they're a Graphcool user already or not, the email will be different. Thanks everyone for your participation 🙏
