### ISSUE TITLE
User Variable in Mutation Callbacks

### ISSUE THREAD

**Issue by marktani** [graphcool/feature-requests#124]
Expose a `$userId: ID` variable in the mutation callback payload schema, similar to the one in permission queries.

If the mutation that triggered the callback was authenticated, this contains the id of the user, otherwise it's `null`.

**Comment by laxgoalie392** [comment]
would be a great feature to have!

**Comment by ts** [comment]
Definitely fits in with our use case! (apologies for the "me too" comment)

**Comment by marktani** [comment]
This will be tackled as part of #219.
