### ISSUE TITLE
Integration with Apollo Optics

### ISSUE THREAD

**Issue by jvbianchi** [graphcool/feature-requests#133]
It would be very useful some kind of integration with Apollo Optics (http://www.apollodata.com/optics).

**Comment by marktani** [comment]
Thanks for the feature request! That's already on our radar and will be done as part of feature request #63.

**Comment by jhalborg** [comment]
Just to clarify, does this mean that you've completely decided to drop any plans for an Optics integration, and just going to roll your own dashboard exclusively?

**Comment by marktani** [comment]
No, we're still very much looking into integrating with Apollo Optics, but the two are not fully identical. We rather decided to build the dashboard _first_ 🙂
