### ISSUE TITLE
Unique constraints are broken on long strings

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/feature-requests#153]
I believe that unique key constraints are broken.

**Schema**
On Project `cj0z18pxogs6s0114pqi4pf0a `, I've created a simple model:

```type UniqueTest {
  createdAt: DateTime!
  id: ID!
  uniqueField: String!
  updatedAt: DateTime!
}
```
The `uniqueField` Field has a unique constraint.

**Use Case**

Adding nodes with the following values for `uniqueField` fails, via console or via query:

`https://techcrunch.com/2012/10/29/pandoras-new-ios-and-android-apps-get-the-facebook-treatment-listening-timelines-activity-feeds-and-social-sharing-features-to-do-battle-with-spotify-and-perhaps-apple/#comments`
`https://techcrunch.com/2012/10/29/pandoras-new-ios-and-android-apps-get-the-facebook-treatment-listening-timelines-activity-feeds-and-social-sharing-features-to-do-battle-with-spotify-and-perhaps-apple/`

The error message clearly states that the unique constraint is violated:

```
Performing that mutation would violate a unique key constraint. The data you supplied is: {\n  "uniqueField": "Some(https://techcrunch.com/2012/10/29/pandoras-new-ios-and-android-apps-get-the-facebook-treatment-listening-timelines-activity-feeds-and-social-sharing-features-to-do-battle-with-spotify-and-perhaps-apple/)"\n}
```

It does not happen for short strings, like `test` and `test#asdf`. 

**Expected result**

Smooth create operation.

**Comment by ejoebstl** [comment]
Apparently, this is a known limitation. 

Thanks to @sorenbs for pointing that out in slack.

**Comment by marktani** [comment]
for reference: https://www.graph.cool/docs/reference/platform/fields-teizeit5se/#unique

> Please note that only the first 191 characters in a String field are considered for uniqueness. Storing two different strings is not possible if the first 191 characters are the same.
