### ISSUE TITLE
Subscription to nested nodes

### ISSUE THREAD

**Issue by ragnorc** [graphcool/feature-requests#163]
It would be great if subscriptions also worked for nested nodes. E.g.: If somebody wants to subscribe to new posts and these posts are a relation in the current user.

**Comment by marktani** [comment]
You can subscribe to new posts of a specific user like this:

```graphql
subscription {
  Post(filter: {
    mutation_in: [CREATED],
    node: {
      user: {
        id: $userId
      }
    }
  }) {
    id
  }
}
```

Or are you talking about something else?

**Comment by marktani** [comment]
Clarified that my suggestion above was the right approach here :slightly_smiling_face:

**Comment by marktani** [comment]
#146 is a related feature quest for relation triggers of subscriptions
