### ISSUE TITLE
File access permissions

### ISSUE THREAD

**Issue by sedubois** [graphcool/feature-requests#166]
As the doc describes: "The file itself is publicly available at the url of the file node, so everyone who knows the file secret and your project id has access to your file!"

Some files should only be accessible with proper headers. There should be permission levels, the same way as for the rest of the API. Need to prevent access from e.g. logged-out users, or users which don't have an active subscription to our product. So there needs to be a way to configure different access levels for different users based on some rules.

Thanks for the good work so far!

**Comment by marktani** [comment]
Thanks for your feedback! I'm closing this in favor of #143.
