### ISSUE TITLE
OrderBy and Filter by _QueryMeta!

### ISSUE THREAD

**Issue by THook** [graphcool/feature-requests#167]
I would like to orderBy and filter by meta information. Considering a many-to-many relation between Post and Tags :

`query listItemsAndTagsBycategory($categoryName: String!) {
  allItems(
orderBy: _tagsMeta_count_DESC
filter: {
_tagsMeta_count_gt: 10
}
  ) 
  {
id
itemTitle
  }`

**Comment by marktani** [comment]
Thanks for the suggestion! Closing in favor of #110 #70.
