### ISSUE TITLE
Modifying files

### ISSUE THREAD

**Issue by sedubois** [graphcool/feature-requests#176]
It would be great to have a way to modify files themselves in the File API. E.g I uploaded several audio files and have been re-editing some of them which contained mistakes. Now the only way AFAIK is to create a new file, modify all relations to point to this new file, then delete the old one. But this is cumbersome and also destroys the file history e.g when was it first created etc.

**Comment by lucfranken** [comment]
Maybe separate the node in File from the actual URL. I think the url of the file should never ever change.

**Comment by marktani** [comment]
Closing in favor of #261.

**Comment by sedubois** [comment]
Oh yes 😅
