### ISSUE TITLE
Error in generate code example

### ISSUE THREAD

**Issue by Gregoirevda** [graphcool/feature-requests#181]
const client = new Lokka({
    transport: new Transport(
        'URL',
        // headers: {
        //   {
        //     Authorization: 'Bearer YOUR_AUTH_TOKEN',
        //   }
        // },
    )
});

should be

const client = new Lokka({
    transport: new Transport(
        'URL',
        // {
        //    Authorization: 'Bearer YOUR_AUTH_TOKEN',
        // },
    )
});

**Comment by marktani** [comment]
Hey @Gregoirevda! Thanks for your report. You can refer to [the Lokka docs](https://github.com/kadirahq/lokka-transport-http#send-custom-headers), the additional `headers` object is needed indeed.

**Comment by Gregoirevda** [comment]
Oh yes, but the problem is the syntax. You pass a key value as 2nd parameter, not an Object.
And you have an Object in an Object

{
   {
      Authorization: 'Bearer YOUR_AUTH_TOKEN',
   }
 }

**Comment by marktani** [comment]
You're right. I created a corresponding issue report here: https://github.com/graphcool/console/issues/857

Thanks :raised_hands:

**Comment by timsuchanek** [comment]
closing and opening for testing scope :)
