### ISSUE TITLE
Graphcool CLI

### ISSUE THREAD

**Issue by schickling** [graphcool/feature-requests#184]
A CLI to manage your Graphcool project as an alternative to the Graphcool Console. Will have similar capabilities as [graphql-up](https://github.com/graphcool/graphql-up).

**Comment by marktani** [comment]
This is now available: https://github.com/graphcool/graphcool-cli/
For more information [read the docs](https://www.graph.cool/docs/reference/cli/project-files-ow2yei7mew/) and the guide for [multi environment development](https://www.graph.cool/docs/tutorials/cli-multi-staging-workflow-ex4wo4zaep/).
