### ISSUE TITLE
Guest/Anonymous Authentication

### ISSUE THREAD

**Issue by marktani** [graphcool/feature-requests#190]
This feature provides authentication without the user actually entering any credentials. This is typically used for situations with anonymous users that should still be authenticated.

**Comment by marktani** [comment]
This is now released, [read more in the docs](https://www.graph.cool/docs/reference/integrations/anonymous-auth-ieph6iujah/).

**Comment by kylejones** [comment]
The docs on this are no longer available at that URL. Have they moved somewhere else?

**Comment by marktani** [comment]
We're phasing out existing authentication providers and are replacing it with the concept of custom authentication. It should be pretty straightforward to implement anonymous authentication using [schema extensions](https://www.graph.cool/forum/t/feedback-schema-extensions-beta/405?u=nilan). Could you PM me in the Forum to discuss this further? 🙂
