### ISSUE TITLE
Wrap RESTful APIs with GraphQL queries

### ISSUE THREAD

**Issue by tim-soft** [graphcool/feature-requests#193]
I may be missing something here, but Graph.cool doesn't appear to allow any custom code/resolvers when getting data for a query.

In a traditional GraphQL server, it would be very straightforward to setup a query that fetches data from a rest API and returns the results.

Resolver functions for queries are a fundamental component of GraphQL!

**Comment by marktani** [comment]
Thanks for this feature request! This is already covered by #40, so I'm closing this one 🙂
