### ISSUE TITLE
Impersonate User

### ISSUE THREAD

**Issue by jvbianchi** [graphcool/feature-requests#194]
Often administrators need to impersonate other users for testing or troubleshooting purposes. 

[Auth0 link explaining this](https://auth0.com/docs/user-profile/user-impersonation).

**Comment by marktani** [comment]
Is this about Auth0? If you need to impersonate an Auth0 user you can generate a token that corresponds to their account.

**Comment by jvbianchi** [comment]
This would be for folks that don't want to use auth0.

**Comment by marktani** [comment]
This can now be implemented using the new beta feature "Schema Extensions". If you're interested in participating in the beta program, please reach out to me in Slack 🙂
