### ISSUE TITLE
Search into related nodes

### ISSUE THREAD

**Issue by sedubois** [graphcool/feature-requests#20]
Add ability to filter on related nodes. For example, getting only `User`s which have associated `Track`s:

```
{
  viewer {
    allUsers(filter: ???) {
      edges {
        node {
          slug
          tracks {
            edges {
              node {
                title
              }
            }
          }
        }
      }
    }
  }
}
```

Without filter, this could return:

```
{
  "data": {
    "viewer": {
      "allUsers": {
        "edges": [
          {
            "node": {
              "slug": "user-without-tracks",
              "tracks": {
                "edges": []
              }
            }
          },
          {
            "node": {
              "slug": "user-with-tracks",
              "tracks": {
                "edges": [
                  {
                    "node": {
                      "title": "Some Awesome Track"
                    }
                  }
                ]
              }
            }
          }
        ]
      }
    }
  }
}
```

`user-without-tracks` shouldn't be returned.

Maybe this relates to https://github.com/graphcool/feature-requests/issues/2.

**Comment by schickling** [comment]
Very good point. This is already WIP. 🎉

**Comment by emolr** [comment]
I needed this as well to show posts related to tags, so i created this (rather ugly but working) temporary solution in angular 2. 
https://gist.github.com/emolr/f2eaf46612ca7bbb47b6a814180da719

It does the job for now, but is of course pretty slow compared to a single request, but it works, so i spend the extra time on a good loading animation hehe

**Comment by philcockfield** [comment]
I'd really like this too - and is core to the kind of structure I'm wishing to manage within GraphQL.  Here's some details my use-case…

![image](https://cloud.githubusercontent.com/assets/185555/21331590/24dcd2c0-c6a8-11e6-97ad-3a9a6207ac48.png)

I am representing a deep tree structure, with each node called say "`Item`" that has a collection of child `Item`'s and a single parent `Item`.

I'd like to be able query for:
- any `item` with a parent ID of `x`.
- any `item` with a parent ID of `undefined`.
- return the item with the `children` items including a specified depth of grand-children into the tree.

Thanks!

**Comment by philcockfield** [comment]
Hey guys - any clue as to whether this is something that might be implemented in the near-ish future?  I need to make a decision somewhat soon as to whether to use Graph.cool, and this is a blocker for me.  

Thanks!

**Comment by schickling** [comment]
Hey @philcockfield! We're already working on this feature. We're expecting to release this in January. Hope that works for you?

**Comment by sedubois** [comment]
Meanwhile @philcockfield you might be able to filter client-side: https://github.com/RelateNow/relate/blob/9dc89b460410b878bc2574af6043f79f86a1f5b3/containers/Users.js#L16

**Comment by philcockfield** [comment]
That's awesome @schickling. I really want to stick with graphcool. 
What is the query parameters going to look like. Can you post your current API design/intentions?  Even if they my change 😃

**Comment by philcockfield** [comment]
@sedubois - thanks for that stop-gap for filtering on the client.  To be clear, that's pulling the entire data-set, then just running filters client side right?

That will certainly let me proceed with GraphCool for everything else, then refactor this when this feature is complete (in Jan)

**Comment by sedubois** [comment]
@philcockfield yes, should work while you don't have too much data.

**Comment by sorenbs** [comment]
We are starting the implementation of this feature this week. 

Feedback is highly appreciated at https://gist.github.com/sorenbs/dec072b8b4df0ab6cbd441861a53eaf9

**Comment by schickling** [comment]
This is now possible using both the Simple and the Relay API. 🎉 

You can read more about this feature here: https://www.graph.cool/docs/reference/simple-api/filtering-by-field-xookaexai0#relation-filters

**Comment by sedubois** [comment]
Thanks @schickling for that documentation! 

Let's say I have a User model and a Track model, with a one-to-many `tracks` relationship. How would I query all users which have at least one track?

**Comment by sedubois** [comment]
This works but is a bit smelly:

```js
{
  allUsers(filter: {
    tracks_some: {
      id_not: "dummy"
    }
  }) {
    givenName
  }
}
```

**Comment by marktani** [comment]
Something like that is the way to go. A different solution:
{
  allUsers(filter: {
    tracks_some: {
      # query all that have been created in the past (2017-02-06-16:13:39 is now)
      createdAt_lt: "2017-02-06-16:13:39"
    }
  }) {
    givenName
  }
}

**Comment by sedubois** [comment]
OK. Now I actually have a second relation `retreats` with model Retreat. How do I select all users who have at least one track or at least one retreat? This gives an empty list:
```js
{
  allMembers(filter: {
    OR: [{
      retreats_some: {
        id_not: "dummy"
      }
      tracks_some: {
        id_not: "dummy"
      }
    }]
  }) {
    givenName
  }
}
```

**Comment by marktani** [comment]
```
{
  allUsers(filter: {
    OR: [{
     retreats_some: {
        id_not: "dummy"
      }
    }, {
      tracks_some: {
        id_not: "dummy"
      }
    }]
  }) {
    givenName
  }
}
```

You need to pass the different conditions as elements of the list argument `OR`.

**Comment by sedubois** [comment]
Ahh that was nasty, those two missing braces 😄 thanks @marktani!
