### ISSUE TITLE
Server-side rendering (SSR)

### ISSUE THREAD

**Issue by sedubois** [graphcool/feature-requests#21]
React apps can use libraries such as [`isomorphic-relay`](https://github.com/denvned/isomorphic-relay) to get server-side rendering for the initial page render. However such libraries require running on a dedicated GraphQL server, but there is no such server when using graph.cool as a backend. It would thus be great for graph.cool to provide these HTML and JS pre-rendering endpoints.

**Comment by schickling** [comment]
I think this isn't something we would directly build into our system but rather make it really easy to put some kind of proxy in front of your web app. We'll look into that over the next couple of weeks and see what kind of solution we can present by then!

Keep posting these great proposals! :shipit:

**Comment by sedubois** [comment]
The way I explore this currently is with Next.js: it provides a kind of isomorphic app with SSR, which I configured to talk to Graph.cool using Apollo (both on the server and browser sides). With such a solution, no need to do anything more on Graph.cool side 👍 but maybe others would want a single server.

**Comment by schickling** [comment]
Thanks for the update @sedubois. We'll reach out to you to see how we could simplify this process further for other customers. We'll write an update here as soon as available.

**Comment by sedubois** [comment]
I've been continuing to simply use Next.js for this. Maybe this could just be closed.

**Comment by marktani** [comment]
For further reference, these are projects with SSR using nextjs and Graphcool: 
https://github.com/zeit/next.js/tree/master/examples/with-apollo
https://github.com/relatenow/relate

Other frameworks also support this, for example Vue: https://vuejs.org/v2/guide/ssr.html

**Comment by dohomi** [comment]
As a sidenode on this matter: for `VUE2` users `vue-apollo` is being able to fetch through `apolloClient` the queries server side as well. `isomorphic-fetch` is the only requirement to make this work.
