### ISSUE TITLE
Geolocation Datatypes

### ISSUE THREAD

**Issue by cto-studiopass** [graphcool/feature-requests#22]
Support location field type in Model. This is an important feature for integration with Algolia. 

ex: 
 _geoloc: {
      lat: 40.639751,
      lng: -73.778925
    }

It must be also possible to have a list of locations. Use case where one wants to record the last 3 locations the user visited in database.

ex:
_geoloc: [
  { "lat": 47.279430, "lng": 5.106450 },
  { "lat": 47.293228, "lng": 5.004570 },
  { "lat": 47.316669, "lng": 5.016670 }
]

**Comment by schickling** [comment]
Thanks for bringing this up @StudioPassDE. We look into this as soon as possible!

**Comment by mypark** [comment]
+1

**Comment by sorenbs** [comment]
Aurora just released Spatial Indexes, so we are no longer blocked on this https://aws.amazon.com/blogs/aws/amazon-aurora-update-spatial-indexing-and-zero-downtime-patching/

**Comment by marktani** [comment]
See here how to make this work using the Algolia Integration: https://www.graph.cool/docs/tutorials/algolia-auto-syncing-for-graphql-backends-aroozee9zu#algolia-geosearch

**Comment by marktani** [comment]
See feature request for Geolocation Datatype #28
