### ISSUE TITLE
Better npm package support

### ISSUE THREAD

**Issue by marktani** [graphcool/feature-requests#226]

**Comment by heymartinadams** [comment]
Is there any workaround if our functions require npm packages currently not available? In my case, I’d require SendPulse (not to be confused with SendGrid): https://github.com/sendpulse/sendpulse-rest-api-node.js

**Comment by kbrandwijk** [comment]
You can use an external webhook, at webtask.io.

**Comment by heymartinadams** [comment]
Thanks, @kbrandwijk.

**Comment by kbrandwijk** [comment]
With regards to the inline functions, just expose the meta property of the container. Adding a `wt-node-dependencies` meta field to the webtask enables support for any package you pass in...

**Comment by heymartinadams** [comment]
That just totally went over my head, @kbrandwijk 🤣

**Comment by kbrandwijk** [comment]
@heymartinadams Don't worry, it was directed at Graphcool. It's something they could change on their side to support this, it's not something you can do as a user.

**Comment by phra** [comment]
you can take inspiration from [runkit](https://runkit.com/home) that is already supporting every existing npm module in their online code editor.

**Comment by kbrandwijk** [comment]
Is this still an issue? Afaik you can already require any package now...

**Comment by phra** [comment]
@kbrandwijk i didn't know that, i've been using apollo graphql server so i've still to play with graph.cool service. if it's confirmed we should close this ticket.

**Comment by marktani** [comment]
Right, by now, all packages are supposed to be supported.

There are two known bugs where this is not the case: https://github.com/graphcool/api-bugs/issues/170 and https://github.com/graphcool/api-bugs/issues/225.

**Comment by stuhlmueller** [comment]
Is it possible to require private packages?

What's the recommended approach for functions that have a more complex spec than can easily fit into a single file? Webhooks?

**Comment by marktani** [comment]
Neither private packages nor multiple files are supported. Feel free to open a new feature request 🙂
