### ISSUE TITLE
Permanent Auth Token User

### ISSUE THREAD

**Issue by lastmjs** [graphcool/feature-requests#228]
Right now permanent auth tokens provide full read and write access to everything in the database, as far as I understand. Blanket access is undesirable, as I'm sure there are use-cases where you want more fine-grained control. For example, I have a small server function that needs access to only a few entities in my schema, but the permanent auth token I'm using for that server function has access to the entirety of the database. That leaves a larger possible attack vector that is unnecessary.

My proposal is that permanent auth tokens are assigned to a special type of user unique to the permanent auth token (i.e. a server user). That way authorizations and permission queries could work exactly as they do currently. All you would need to do is reference the user id or other properties of the user associated with the permanent auth token.

Anyway, those are my thoughts on the matter.

**Comment by marktani** [comment]
Thanks for the great input! I transferred it over to feature request #80.
