### ISSUE TITLE
It is not possible to set null as a default value in the console

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/feature-requests#233]
It is impossible to set null as a default value for any field in the console. 

If null is selected as default value, the "Update Field" button will simply vanish. 

<img width="645" alt="screenshot 2017-06-09 00 00 43" src="https://user-images.githubusercontent.com/1852126/26952674-cfb2dfe4-4ca6-11e7-97d5-389ed5991697.png">
<img width="635" alt="screenshot 2017-06-09 00 00 58" src="https://user-images.githubusercontent.com/1852126/26952675-cfb314a0-4ca6-11e7-96bc-16c4f77329a7.png">

**Comment by marktani** [comment]
Thanks for the report! I migrated it over to the Console bugtracker: https://github.com/graphcool/console/issues/1070
