### ISSUE TITLE
Unicity per related node

### ISSUE THREAD

**Issue by sedubois** [graphcool/feature-requests#24]
I want to create two models, `User` and `Org` which both have a `slug`, ensuring that this slug is unique across all users and orgs (similar to GitHub and such sites). I don't think graph.cool currently allows this?

**Comment by sorenbs** [comment]
One approach that might or might not work based on your use case is to create a separate Slug model with a unique slug field. Then you can either reference this from the User and Org models or simply use it as a "slug generator" that simply verifies that a slug is unique before you assign it to a new User or Org.

Would either of these solutions work for you?

**Comment by schickling** [comment]
That being said, we should probably provide a more powerful solution to create multi-field/multi-model constraints.

**Comment by sedubois** [comment]
Agreed with both comments, the stated workarounds is OK for now, it's just not very clean and maintainable. Something more intuitive would be very appreciated.

**Comment by sedubois** [comment]
Would you have news on this?

**Comment by marktani** [comment]
We're starting to test this feature with a few projects, I'll contact you for more details :)

**Comment by marktani** [comment]
In this case, adding a `Slug` model with a unique `key: String!` field is the way to go.

**Comment by sedubois** [comment]
It's actually still annoying, now the field selector looks like this 😅 :

```
    slug {
      slug
    }
```

**Comment by marktani** [comment]
That's why I'd suggest naming the field something like `key`, `title`, `name`.

**Comment by sedubois** [comment]
OK, next question is that now I lose the ability to select a `User(slug: $slug)`, because I cannot add a unique constraint on the relation. How do I work around that?

**Comment by marktani** [comment]
I suggest waiting for #23 and then checking the unicity when creating and updating users or organizations.

**Comment by sedubois** [comment]
Actually, couldn't you instrument the code to mark the linked field as unique? After all, it __is__ unique in the linked model. That sounds simple enough and would answer the issue I think?

**Comment by marktani** [comment]
See #65.

**Comment by kbrandwijk** [comment]
Unicity across different models could be solved using a scope parameter for @isUnique, and a @scope directive on Types, so you have some kind of 'grouping' for this kind of functionality.

**Comment by kbrandwijk** [comment]
Or maybe when interfaces are implemented, and you specify a isUnique directive on an interface field, that field will be unique across all Types that implement the interface.

**Comment by sorenbs** [comment]
Please see proposed spec in https://github.com/graphcool/framework/issues/1300
