### ISSUE TITLE
Expose ENUMS as queryables

### ISSUE THREAD

**Issue by dsbert** [graphcool/feature-requests#249]
Currently there does not seem to be any way to query an enum to retrieve all possible values.

**Comment by marktani** [comment]
This can be done using an introspection query as shown [in this article](https://www.graph.cool/docs/faq/graphql-introspection-queries-shoe5xailo/#query-all-enum-values) 🙂

**Comment by dsbert** [comment]
@marktani I missed this in the documentation, thank you.
