### ISSUE TITLE
Subscriptions

### ISSUE THREAD

**Issue by schickling** [graphcool/feature-requests#26]

**Comment by mkozhukharenko** [comment]
will this feature  be released till 2017? 
And, as I can guess, subscription will work only with Apollo, isn't it?

**Comment by sorenbs** [comment]
Hi Nikolay. We are currently testing this feature in a closed beta and expect to officially release it within two weeks. Would you be interested in participating in the closed beta program?

**Comment by mkozhukharenko** [comment]
@sorenbs yes, I'd like to.

What should I do for this?

**Comment by schickling** [comment]
We'll reach out to you! 👋

**Comment by andreasbhansen** [comment]
@sorenbs @schickling Would it be possible to be enrolled in the beta programme? Working on an application which depends fully on real-time/subscriptions-based data, which at the moment is the only feature lacking (for us) in GraphCool. 🙏

**Comment by lewisblackwood** [comment]
@schickling @sorenbs Would be keen to get involved in the closed beta too, if possible!

**Comment by sorenbs** [comment]
Hi @lewisblackwood Subscriptions are still in beta. While we don't anticipate any big changes we might adjust the api slightly, so just be aware of that. You can read a quick introduction here https://gist.github.com/sorenbs/18938a93afa87bd68e91820d7ad1b4da

I am super excited that you want to help us test this feature. If you have any question or run into issues, please get back to me here, in slack or via email.

**Comment by marktani** [comment]
Thanks everyone for your feedback, we put a lot of work into the new Subscriptions API and are happy to release it :tada: Read the [full announcement](https://www.graph.cool/blog/2017-02-28-introducing-graphql-subscriptions-in4ohtae4e) or join the [worldchat live demo](https://demo.graph.cool/worldchat/).

If you want to get started with GraphQL Subscriptions, you can follow the [Subscriptions Tutorial](https://www.graph.cool/docs/tutorials/worldchat-subscriptions-example-ui0eizishe).
