### ISSUE TITLE
Querying required fields with insufficient permissions should also return null?

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/feature-requests#260]
In the current implementation, querying a required field on the root type of the query returns null for the entire Type, and if all results are null, no data is returned.

Although required is useful for creating/updating records, it doesn't make that much sense that it also has effect on the query results.

Proposal: if a user does not have read permissions on a field, the query should always return null for that field, regardless of the required flag.

**Comment by marktani** [comment]
I created a more general feature request: #280.

**Comment by marktani** [comment]
Currently, a field that is specified as "required" in the data schema will both be required in the according input argument of the create mutation and also whenever the field is returned in a query.

When a required field in a query would return null, the entire wrapping field will be "nullified". Sometimes this is referred to as "null bubbling". You can see how this works [in this FAQ article](https://www.graph.cool/docs/faq/graphcool-insufficient-permissions-query-response-noohie9hai/).

> Proposal: if a user does not have read permissions on a field, the query should always return null for that field, regardless of the required flag.

The proposed behaviour can only be achieved by not specifying the field part of the type as required. So I think #280 is the right solution to this problem.

**Comment by kbrandwijk** [comment]
I agree, this one can be closed because of #280. I confused closing this one with #274, my bad...
