### ISSUE TITLE
Add support for Geopoints

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/feature-requests#277]
Basics:
- Create a Type to store Geopoints in one field (long/lat/alt)
- Create basic filters for Geopoints (radius, rectangle)

Bonus:
- Build goodies (like a `getMaplink` query or field parameter on a Geopoint field to get a google maps link to a Geopoint, and `drivingDistance` instead of `radius` using Google maps API in the backend)

**Comment by marktani** [comment]
Closing as duplicate of #28. 🙂

**Comment by kbrandwijk** [comment]
Github issue search :-1:...
