### ISSUE TITLE
Add, and keep track of, version field for RP, PQ, SSS

### ISSUE THREAD

**Issue by kbrandwijk** [graphcool/feature-requests#299]
Currently, only project schema has a version field. It would be helpful for a number of development workflow usecases, if RP, PQ and SSS would have their own version field that is tracked automatically like the project schema version.

Is somewhat related to https://github.com/graphcool/api-bugs/issues/148, because I think as soon as this is implemented, the project schema version changes can be limited to only changes to the schema.

**Comment by marktani** [comment]
Thanks for your suggestion! I adjusted the description of [this feature request](https://github.com/graphcool/feature-requests/issues/213) to consider a versioning concept as well. Let's continue the discussion there!
