### ISSUE TITLE
Implement mutation callback testing feature

### ISSUE THREAD

**Issue by timsuchanek** [graphcool/feature-requests#30]
![screen shot 2016-07-30 at 19 28 46](https://cloud.githubusercontent.com/assets/1567498/17415862/dce2852e-5a8b-11e6-8fdb-fa9283f151d1.png)

**Comment by joeltello** [comment]
This would be very useful!!!!

**Comment by marktani** [comment]
This is now available as part of the [Functions feature](https://www.graph.cool/docs/reference/functions/overview-boo6uteemo/). In the fullscreen mode you can test your function with test data:
![image](https://cloud.githubusercontent.com/assets/1780597/26762429/a414cf44-4942-11e7-8ba7-ebeeb7f9fc3e.png)

**Comment by mattfysh** [comment]
@marktani are there any limitations on the test run? if I try to use fetch, it hits the 15 second timeout. Running the same function locally works though, and I've checked the network tab in chrome and the /create endpoint works, its just the /execute that fails due to timeout
