### ISSUE TITLE
subscriptions should be triggered if relations of schema is updated

### ISSUE THREAD

**Issue by dohomi** [graphcool/feature-requests#301]
Hello,

currently subscriptions only being triggered if scalar values of schema being updated. This might be misleading and it would be a great benefit, if subscriptions being triggered on any related schema change. This would make reactivity more predictable and the use of subscriptions more reliable what the developer expects.

Thanks!

**Comment by kbrandwijk** [comment]
See https://github.com/graphcool/feature-requests/issues/146
