### ISSUE TITLE
Add Query for a Random Entry

### ISSUE THREAD

**Issue by Plinpod** [graphcool/feature-requests#303]
It would be useful to be able to get single random database entries with one simple query. 

Such as using 
```
query {
  allPosts{
    id
}
}
```
To get all Posts

It would be great to be able to do
```
query {
  randomPost{
   id
  }
}
```
Or something along those lines to be able to get a random entry.

```
query {
   Post(id: "*"){
     title
   }
}
```

Allowing for a wildcard in the id field of a query would also be a possible solution to allow for a random entry.

**Comment by marktani** [comment]
Thanks for the suggestion! This has been suggested before, so I'm closing this: #114.
