### ISSUE TITLE
Deeper nested mutations

### ISSUE THREAD

**Issue by danmkent** [graphcool/feature-requests#313]
I have a use case for nesting create mutations one level deeper than the current limit of 3 levels down from the outer mutation.

It would be great if I could do a single mutation to create my hierarchy rather than having to split the operation across multiple mutations.

**Comment by sorenbs** [comment]
Do you think 4 levels would be enough for all your use cases?

**Comment by danmkent** [comment]
The extra level would cover my current use cases and I don't anticipate adding any more.

**Comment by marktani** [comment]
I've seen cases where 5 or 6 levels were needed, as well 🙂

**Comment by sorenbs** [comment]
🙈

**Comment by JensMadsen** [comment]
Performance wise it would be better to enable uploading a nested json instead?

**Comment by sorenbs** [comment]
@danmkent We now support 4 levels of nesting :-)

**Comment by danmkent** [comment]
Awesome - thanks for that. I will be able to refactor some messy code now!
