### ISSUE TITLE
pull code for Functions with graphcool cli

### ISSUE THREAD

**Issue by danmkent** [graphcool/feature-requests#328]
It would be really useful if the graphcool pull CLI command would pull the configuration of server side Functions as well as the schema.

If it did this, it would be easy to include the functions in source control along with everything else.

It could also lead in the future to enabling easy client side editing of functions and then using graphcool push to upload the changes

I would not suggest putting all the function code in the project.graphcool file as it would get very unwieldy.  I think it would be better to include a manifest of functions in the project.graphcool (wuth config info for each) and then put the JS code for each function in a separate file (likely in a directory called  graphcool-functions  or similar)

**Comment by marktani** [comment]
Thanks for this suggestion! This is part of feature request #213 🙂
