### ISSUE TITLE
Timeout with too many requests

### ISSUE THREAD

**Issue by elbracht** [graphcool/feature-requests#345]
I get the following timeout error with too many requests:

```
reason: connect ETIMEDOUT 52.85.183.187:443
```

I use the `isomorphic-fetch` package to send mutations in a loop. After about 200 requests i get the timeout error.

Am I doing something wrong?

**Comment by marktani** [comment]
Hey, a very similar question was asked [in the Forum](https://www.graph.cool/forum/t/import-data-into-node/359?u=nilan) a while ago. Please refer to the answers there. If you have more questions after reading the thread, feel free to open a new one. Thanks 🙏
