### ISSUE TITLE
Support list types in nested mutations

### ISSUE THREAD

**Issue by schickling** [graphcool/feature-requests#46]
Would be great if something like the following would work:

```graphql
mutation {
  createItem(
    title: "Hello world"
    subitems: [{
      title: "sub item 1"
    }, {
      title: "sub item 2"
    }]
}
```

**Comment by uesteibar** [comment]
+1 to this, currently managing many-to-many relationships is kinda hard...

great job otherwise! Love the platform :)

**Comment by uesteibar** [comment]
Actually, I'd try to make it a bit simpler and just support something like

```
mutation {
  createItem(title: "whatever", authorIds: ["author-id-1", "author-id-2"])
}
```

I think that would be pretty straight forward. What do you think @schickling ?

**Comment by schickling** [comment]
Great news @uesteibar, we're currently implementing this functionality and should be rolling it out over the next couple of days. Excited to hear your feedback on it.

About your API suggestion: Yes, it will be possible to support both an array of IDs or an array of actually nested nodes. (You can even combine both if needed.)

**Comment by uesteibar** [comment]
@schickling that's awesome, thanks!! So looking forward to try it out 😸

**Comment by uesteibar** [comment]
@schickling did this happen? haven't got any notification and can't find it in the docs 😿

**Comment by marktani** [comment]
It's not updated in the docs yet because there are some problematic edge cases. However this is already available in the API, you can already declare both multiple nested ids and objects at the same time :)

**Comment by marktani** [comment]
@uesteibar after further testing this should now be ready! If you experience a problem with lists and nested mutations, please create an issue at https://github.com/graphcool/console/issues.

**Comment by uesteibar** [comment]
@marktani awesome! I'll give it a try and give you some feedback, thanks!
