### ISSUE TITLE
refreshToken mutation endpoint

### ISSUE THREAD

**Issue by mypark** [graphcool/feature-requests#71]
**Given**: an existing user with a valid authorized token
**Then**: endpoint should give me a fresh new token that extends the expiration another 30 days - or whatever time period is the graphcool default.

It can return something very similar to the login mutation

This will allow users using a mobile app to not have to re-log in every x days as long as they have used the app regularly within that time period.

**Comment by schickling** [comment]
This is pretty high on our priority list as part of #39

**Comment by mypark** [comment]
Ok will close as duplicate
