### ISSUE TITLE
Allow createUser to be authenticated/restricted only to the current user

### ISSUE THREAD

**Issue by morgothulhu** [graphcool/feature-requests#89]
Scenario is self-served portal.

Any user can sign-in using Auth0, thus get their id_token.
Using https://jwt.io/, the encoded id_token can be modified, to alter the ```sub``` field
Then the ```createUser(authProvider: {auth0: {idToken: $idToken}} ...``` mutation can be invoked with the forged id_token.

Two possible solutions I see:
- allow 'authenticated' condition to allow matching user (as long as the proper Authentication Bearer idToken) is passed even if the row is not yet created in User
- replace auth0: {idToken} to use JWT (as mentioned [here](https://auth0.com/blog/building-an-instagram-clone-with-graphql-and-auth0/)) to validate on graph.cool proper signature

**Comment by sorenbs** [comment]
Thanks for reporting this @morgothulhu 

I will look into this today and get back to you.

**Comment by sorenbs** [comment]
This is resolved by validating the jwt. Thanks again @morgothulhu
