### ISSUE TITLE
Exporting configuration

### ISSUE THREAD

**Issue by ejoebstl** [graphcool/feature-requests#97]
Besides exporting the schema, it should also be possible to export further configuration, like 

* configured webhooks
* configured auth providers
* permissions

Especially webhooks and permissions are important for creating new projects for testing or staging.

**Comment by marktani** [comment]
Thanks, this makes a lot of sense! Related to #96 as well.

**Comment by kbrandwijk** [comment]
Also, add that possibility to the CLI. Would be really helpful do have a declarative way to define an entire project, with everything in it. Easy for tutorials/boilerplates/example projects too.

**Comment by kbrandwijk** [comment]
Related to #213

**Comment by marktani** [comment]
I'd say this is close enough to #213 to continue the discussion there 🙂
